# Generated by Django 3.0.4 on 2020-05-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('userid', models.CharField(max_length=20)),
                ('hashtags', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('geolocation', models.CharField(max_length=20)),
                ('sentiment_tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
