# Generated by Django 3.0.4 on 2020-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200507_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettestdata',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tweettestdata',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
