# Generated by Django 3.0.6 on 2020-05-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200521_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='education_level',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
