# Generated by Django 3.0.6 on 2020-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200507_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tweetcounts', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=30)),
                ('approval_rate', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
    ]
