# Generated by Django 3.0.6 on 2020-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200521_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='postgraduate_percentage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='education_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
