# Generated by Django 3.0.6 on 2020-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweetresultdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetresultdata',
            name='city_id',
            field=models.CharField(default='Melbourne', max_length=30),
        ),
    ]
