# Generated by Django 3.0.4 on 2020-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettestdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
