# Generated by Django 3.0.6 on 2020-05-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200507_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweettestdata',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tweettestdata',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tweettestdata',
            name='tweetid',
            field=models.CharField(default='000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='tweettestdata',
            name='userid',
            field=models.CharField(default='000000', max_length=20),
        ),
    ]
