- name: create instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_name }}'
    volumes: '{{ os_vol_id }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}' 
  register: os_instance

- debug:
    msg: "Instance {{ item.openstack.name }} creted with IP {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: wait for connection
  wait_for:
    host: '{{ item.openstack.public_v4 }}'
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: TEAM29
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined