# ====================================
# COMP90024 Cluster and Cloud Computing - Assignment 2
# Group 29
# Hongwei Yin 901012
# Cheng Sun 900806
# Xinyi Xu 900966
# Yiran Yao 1144268
# Xiaotao Tan 1032950
# ====================================

- name: create instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_name }}'
    volumes: '{{ item.volume_names }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}' 
  register: os_instance

- debug:
    msg: "Instance {{ item.openstack.name }} created with IP address {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: wait for connection
  wait_for:
    host: '{{ item.openstack.public_v4 }}'
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: TEAM29
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined