- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: get environment arguments
  shell: cat /etc/environment
  register: env_args

- name: set proxy
  become: yes
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    create: yes
  loop: "{{ instance_proxy }}"

- name: install tools
  become: yes
  apt:
    name: ['vim','python3-pip'] 
    state: latest
    install_recommends: no
    update_cache: yes

- name: update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: install setuptools
  become: yes
  pip:
    name: ['setuptools', 'jsondiff']
    state: latest
    executable: pip3