# ====================================
# COMP90024 Cluster and Cloud Computing - Assignment 2
# Group 29
# Hongwei Yin 901012
# Cheng Sun 900806
# Xinyi Xu 900966
# Yiran Yao 1144268
# Xiaotao Tan 1032950
# ====================================

- name: check whether proxy directory exists
  become: yes
  stat:
      path: "{{ docker_proxy_directory }}"
  register: directory_stats

- name: create proxy directory if not yet exist
  become: yes
  file:
      path: "{{ docker_proxy_directory }}"
      state: directory
      mode: 0777
  when: directory_stats.stat.exists == false

- name: copy file from local to server
  become: yes
  copy:
    src: ../../host_vars/http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: 0777

#sudo ls -l /var/run/docker.sock
#permission needs to be changed if attempting to use 'docker' command on instance
- name: check file permission for docker.sock
  become: yes
  stat:
    path: /var/run/docker.sock
  register: fstat

#sudo chmod 666 /var/run/docker.sock
- name: change permission for docker.sock
  become: yes
  file: 
    path: /var/run/docker.sock
    mode: 0666
  when: fstat.stat.mode != "0666"

- name: flush changes & restart Docker service
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker