# ====================================
# COMP90024 Cluster and Cloud Computing - Assignment 2
# Group 29
# Hongwei Yin 901012
# Cheng Sun 900806
# Xinyi Xu 900966
# Yiran Yao 1144268
# Xiaotao Tan 1032950
# ====================================

- include_tasks: mount_volumes.yml
- include_tasks: docker_install.yml
- include_tasks: docker_setup.yml