# Generated by Django 3.0.6 on 2020-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=400)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('geoinfo', models.CharField(blank=True, max_length=80)),
                ('hashtags', models.CharField(blank=True, max_length=200)),
                ('sentiment_tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
