# Generated by Django 3.0.6 on 2020-05-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tid',
            new_name='_id',
        ),
    ]
