- name: install tools
  become: yes
  apt:
    name: ['python3-dev', 'libpq-dev', 'nginx', 'curl', 'git'] 
    state: latest
    install_recommends: no
    update_cache: yes

- name: install
  become: yes
  pip:
    name: ['virtualenv', 'django', 'whitenoise', 'djangorestframework', 'python-dateutil', 'django-jquery', 'django-extensions']
    state: latest
    executable: pip3