# ====================================
# COMP90024 Cluster and Cloud Computing - Assignment 2
# Group 29
# Hongwei Yin 901012
# Cheng Sun 900806
# Xinyi Xu 900966
# Yiran Yao 1144268
# Xiaotao Tan 1032950
# ====================================

- name: install tools
  become: yes
  apt:
    name: ['python3-dev', 'libpq-dev', 'nginx', 'curl', 'git'] 
    state: latest
    install_recommends: no
    update_cache: yes

- name: install
  become: yes
  pip:
    name: ['virtualenv', 'django', 'whitenoise', 'djangorestframework', 'python-dateutil', 'django-jquery', 'django-extensions']
    state: latest
    executable: pip3