- hosts: databases
  become: yes
  tasks: 
    - name: copy folder from local to server
      become: yes
      copy:
        src: .
        dest: /home/ubuntu/
        mode: 0777

- hosts: manager
  become: yes
  tasks:
    - name: populate database
      raw: nohup python3 /home/ubuntu/harvester/addto_db.py 172.26.132.216 historical_data/historical-Geelong.json >nohup1.out 2>&1 &

    