- name: initialise swarm
  become: yes
  docker_swarm:
    advertise_addr: "{{ ansible_eth0['ipv4']['address'] }}"
    state: present
  register: myswarm

- name: get swarm manager token
  shell: sudo docker swarm join-token -q manager
  register: manager_token_result

- debug:
    msg: "{{ manager_token_result }}"  
- set_fact:
    manager_token: "{{ manager_token_result.stdout }}"

- debug:
    msg: "{{ manager_token }}"

- name: get swarm worker token
  shell: sudo docker swarm join-token -q worker
  register: worker_token_result

- set_fact:
    worker_token: "{{ worker_token_result.stdout }}"

# - name: initialise swarm
#   shell: sudo docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}
#   when: "'active' not in swarm_status.stdout_lines"
