- hosts: manager
  gather_facts: true
  tasks:
    - name: copy container start file from local to server
      become: yes
      copy:
        src: ./cluster_master_create.sh
        dest: /home/ubuntu/cluster_master_create.sh
        mode: 0777
    
    - name: copy cluster setup file from local to server
      become: yes
      copy:
        src: ./cluster_master_setup.sh
        dest: /home/ubuntu/cluster_master_setup.sh
        mode: 0777

    # - name: copy file from local to server
    #   become: yes
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: /home/ubuntu/docker-compose.yml
    #     mode: 0777

    - name: copy private key from local to server
      become: yes
      copy:
        src: ~/.ssh/team29.pem
        dest: /home/ubuntu/.ssh/team29.pem
        mode: 0777

    #sudo ls -l /var/run/docker.sock
    #permission needs to be changed if attempting to use 'docker' command on instance
    - name: check file permission for docker.sock
      become: yes
      stat:
        path: /var/run/docker.sock
      register: fstat

    #sudo chmod 666 /var/run/docker.sock
    - name: change permission for docker.sock
      become: yes
      file: 
        path: /var/run/docker.sock
        mode: 0666
      when: fstat.stat.mode != "0666"
    
    - name: run script to start Docker container using CouchDB image on manager node
      become: yes
      raw: cd /home/ubuntu; ./cluster_master_create.sh

- hosts: worker1
  tasks:
    - name: copy file from local to server
      become: yes
      copy:
        src: ./cluster_worker1.sh
        dest: /home/ubuntu/cluster_worker1.sh
        mode: 0777

    - name: check file permission for docker.sock
      become: yes
      stat:
        path: /var/run/docker.sock
      register: fstat

    #sudo chmod 666 /var/run/docker.sock
    - name: change permission for docker.sock
      become: yes
      file: 
        path: /var/run/docker.sock
        mode: 0666
      when: fstat.stat.mode != "0666"
    
    - name: run script to start Docker container using CouchDB image on worker1 node
      become: yes
      raw: cd /home/ubuntu; ./cluster_worker1.sh

- hosts: worker2
  tasks:
    - name: copy file from local to server
      become: yes
      copy:
        src: ./cluster_worker2.sh
        dest: /home/ubuntu/cluster_worker2.sh
        mode: 0777

    - name: check file permission for docker.sock
      become: yes
      stat:
        path: /var/run/docker.sock
      register: fstat

    #sudo chmod 666 /var/run/docker.sock
    - name: change permission for docker.sock
      become: yes
      file: 
        path: /var/run/docker.sock
        mode: 0666
      when: fstat.stat.mode != "0666"
    
    - name: run script to start Docker container using CouchDB image on worker2 node
      become: yes
      raw: cd /home/ubuntu; ./cluster_worker2.sh

- hosts: manager
  gather_facts: true
  tasks:
    - name: run script to set up cluster
      become: yes
      raw: cd /home/ubuntu; ./cluster_master_setup.sh