version: "3.8"
services:
  db: 
    container_name: db
    image: couchdb
    restart: always
    volumes:
      - /home/ubuntu/data:/opt/couchdb/data
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: 'comp90024'
    ports:
      - "5984:5984"
      - "5986:5896"
      - "4369:4369"
      - "9100-9200:9100-9200"